# Generated by Django 3.1.2 on 2020-11-01 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
