# Generated by Django 3.1.2 on 2020-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
